# Generated by Django 4.2.1 on 2025-03-27 06:59

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Achievement",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("description", models.TextField()),
                ("category", models.CharField(blank=True, max_length=500, null=True)),
                ("is_deleted", models.BooleanField(default=False)),
                ("date_created", models.DateTimeField(auto_now_add=True)),
                (
                    "creator",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        related_name="achievement_creator",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "db_table": "achievements",
            },
        ),
        migrations.CreateModel(
            name="Borough",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("name", models.CharField(max_length=255)),
                ("is_deleted", models.BooleanField(default=False)),
                ("date_created", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "db_table": "boroughs",
            },
        ),
        migrations.CreateModel(
            name="BudgetFinancialYear",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("Year", models.CharField(max_length=20)),
                ("BudgetInKES", models.DecimalField(decimal_places=2, max_digits=18)),
                (
                    "remaining_amount",
                    models.DecimalField(decimal_places=2, default=0, max_digits=18),
                ),
                (
                    "absorption_rate",
                    models.DecimalField(decimal_places=2, default=0, max_digits=5),
                ),
                (
                    "expenditure",
                    models.DecimalField(decimal_places=2, default=0, max_digits=18),
                ),
                ("is_deleted", models.BooleanField(default=False)),
                ("reason_for_changing_budget", models.CharField(max_length=255)),
                ("authority_to_change", models.CharField(max_length=50)),
                ("comments", models.CharField(blank=True, max_length=255, null=True)),
            ],
            options={
                "db_table": "financial_years_budget",
            },
        ),
        migrations.CreateModel(
            name="CabinetMemo",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("memoNumber", models.CharField(max_length=20)),
                ("title", models.CharField(max_length=200)),
                ("description", models.CharField(max_length=200)),
                ("concept", models.CharField(max_length=200, null=True)),
                ("goal", models.CharField(max_length=200)),
                ("objective", models.CharField(max_length=200, null=True)),
                ("legal_implication", models.CharField(max_length=200)),
                ("area_of_focus", models.CharField(max_length=200, null=True)),
                ("team_members", models.CharField(max_length=200, null=True)),
                ("funds_source", models.CharField(max_length=200)),
                (
                    "otherFundsSource",
                    models.CharField(blank=True, max_length=200, null=True),
                ),
                (
                    "cabinetMemoFile",
                    models.FileField(blank=True, null=True, upload_to="cabinet_memos/"),
                ),
                ("is_deleted", models.BooleanField(default=False)),
                ("date_created", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "db_table": "cabinet memos",
            },
        ),
        migrations.CreateModel(
            name="Department",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("name", models.CharField(max_length=500)),
                ("date_created", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "db_table": "departments",
            },
        ),
        migrations.CreateModel(
            name="Directorate",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("name", models.CharField(max_length=500)),
                ("date_created", models.DateTimeField(auto_now_add=True)),
                ("is_deleted", models.BooleanField(default=False)),
            ],
            options={
                "db_table": "directorates",
            },
        ),
        migrations.CreateModel(
            name="ProjectSubCategory",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("name", models.CharField(max_length=500)),
                ("is_deleted", models.BooleanField(default=False)),
                ("date_created", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "db_table": "project_sub_categories",
            },
        ),
        migrations.CreateModel(
            name="RRIGoals",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("goal", models.TextField()),
                ("results_leaders", models.JSONField(blank=True, null=True)),
                ("technical_leaders", models.JSONField(blank=True, null=True)),
                ("strategic_leaders", models.JSONField(blank=True, null=True)),
                ("is_deleted", models.BooleanField(default=False)),
                ("date_created", models.DateTimeField(auto_now_add=True)),
                (
                    "creator",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        related_name="goal_creator",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "db_table": "rri_goals",
            },
        ),
        migrations.CreateModel(
            name="Sector",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("name", models.CharField(max_length=500)),
                ("date_created", models.DateTimeField(auto_now_add=True)),
                ("is_deleted", models.BooleanField(default=False)),
            ],
            options={
                "db_table": "sectors",
            },
        ),
        migrations.CreateModel(
            name="SubCounty",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("name", models.CharField(max_length=255)),
                ("is_deleted", models.BooleanField(default=False)),
                ("date_created", models.DateTimeField(auto_now_add=True)),
                (
                    "borough",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="subcounties",
                        to="api.borough",
                    ),
                ),
            ],
            options={
                "db_table": "sub_counties",
            },
        ),
        migrations.CreateModel(
            name="Title",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("name", models.CharField(max_length=500)),
                ("is_deleted", models.BooleanField(default=False)),
                ("date_created", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "db_table": "Titles",
            },
        ),
        migrations.CreateModel(
            name="WorkPlan",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("location", models.JSONField(blank=True, null=True)),
                ("milestone", models.CharField(max_length=500)),
                ("steps", models.JSONField()),
                ("collaborators", models.JSONField(blank=True, null=True)),
                ("start_date", models.DateField()),
                ("end_date", models.DateField()),
                ("budget", models.IntegerField()),
                ("status", models.CharField(max_length=500)),
                ("remarks", models.TextField()),
                ("risks", models.TextField(blank=True, null=True)),
                (
                    "percentage",
                    models.IntegerField(
                        default=0,
                        validators=[
                            django.core.validators.MinValueValidator(0),
                            django.core.validators.MaxValueValidator(100),
                        ],
                    ),
                ),
                ("is_deleted", models.BooleanField(default=False)),
                ("date_created", models.DateTimeField(auto_now_add=True)),
                (
                    "creator",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        related_name="work_plan_creator",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "person_incharge",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        related_name="work_plan_person_incharge",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "rri_goal",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        related_name="work_plan_rri_goal",
                        to="api.rrigoals",
                    ),
                ),
            ],
            options={
                "db_table": "workplans",
            },
        ),
        migrations.CreateModel(
            name="WeeklyReports",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("activities", models.JSONField()),
                ("is_deleted", models.BooleanField(default=False)),
                ("date_created", models.DateTimeField(auto_now_add=True)),
                (
                    "creator",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        related_name="weekly_report_creator",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "workplan",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        related_name="weekly_report_workplan",
                        to="api.workplan",
                    ),
                ),
            ],
            options={
                "db_table": "weekly_reports",
            },
        ),
        migrations.CreateModel(
            name="Wave",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("name", models.CharField(max_length=255)),
                ("start_date", models.DateField()),
                ("end_date", models.DateField()),
                ("budget", models.BigIntegerField(default=0)),
                ("type", models.CharField(default="MAIN", max_length=255)),
                ("standalone", models.CharField(blank=True, max_length=255, null=True)),
                ("mother_id", models.CharField(blank=True, max_length=255, null=True)),
                ("location", models.JSONField(blank=True, null=True)),
                ("members", models.JSONField(blank=True, null=True)),
                ("risks", models.TextField(blank=True, null=True)),
                ("results_leaders", models.JSONField(blank=True, null=True)),
                ("technical_leaders", models.JSONField(blank=True, null=True)),
                ("strategic_leaders", models.JSONField(blank=True, null=True)),
                ("is_deleted", models.BooleanField(default=False)),
                ("date_created", models.DateTimeField(auto_now_add=True)),
                ("no_cabinet_memo", models.BooleanField(default=False)),
                ("no_cabinet_memo_reason", models.TextField(blank=True, null=True)),
                (
                    "cabinet_memo",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        related_name="wave_cab_memo",
                        to="api.cabinetmemo",
                    ),
                ),
                (
                    "directorate",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        related_name="wave_directorate",
                        to="api.directorate",
                    ),
                ),
                (
                    "financial_year",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        related_name="wave_financial_year",
                        to="api.budgetfinancialyear",
                    ),
                ),
                (
                    "sub_category",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        related_name="wave_sub_category",
                        to="api.projectsubcategory",
                    ),
                ),
            ],
            options={
                "db_table": "waves",
            },
        ),
        migrations.CreateModel(
            name="Ward",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("name", models.CharField(max_length=255)),
                ("is_deleted", models.BooleanField(default=False)),
                (
                    "sub_county",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        related_name="wards",
                        to="api.subcounty",
                    ),
                ),
            ],
            options={
                "db_table": "wards",
            },
        ),
        migrations.CreateModel(
            name="ThematicArea",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("area", models.TextField()),
                ("is_deleted", models.BooleanField(default=False)),
                ("date_created", models.DateTimeField(auto_now_add=True)),
                (
                    "directorate",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        related_name="thematic_area_directorate",
                        to="api.directorate",
                    ),
                ),
                (
                    "project",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        related_name="goal_project",
                        to="api.wave",
                    ),
                ),
                (
                    "sector",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        related_name="thematic_area_sector",
                        to="api.sector",
                    ),
                ),
            ],
            options={
                "db_table": "thematic_areas",
            },
        ),
        migrations.CreateModel(
            name="TeamMembers",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("name", models.CharField(max_length=150)),
                ("date_created", models.DateTimeField(auto_now_add=True)),
                (
                    "goal",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        related_name="member_goal",
                        to="api.rrigoals",
                    ),
                ),
            ],
            options={
                "db_table": "team_members",
            },
        ),
        migrations.CreateModel(
            name="SubSector",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("name", models.CharField(max_length=500)),
                ("date_created", models.DateTimeField(auto_now_add=True)),
                ("is_deleted", models.BooleanField(default=False)),
                (
                    "sector",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        related_name="sector",
                        to="api.sector",
                    ),
                ),
            ],
            options={
                "db_table": "sub_sectors",
            },
        ),
        migrations.AddField(
            model_name="rrigoals",
            name="thematic_area",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.DO_NOTHING,
                related_name="thematic_area",
                to="api.thematicarea",
            ),
        ),
        migrations.AddField(
            model_name="rrigoals",
            name="wave",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.DO_NOTHING,
                related_name="wave",
                to="api.wave",
            ),
        ),
        migrations.CreateModel(
            name="ResultChain",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("activities", models.JSONField(blank=True, null=True)),
                ("input", models.JSONField()),
                ("output", models.JSONField()),
                ("outcome", models.JSONField()),
                ("impact", models.JSONField()),
                ("is_deleted", models.BooleanField(default=False)),
                ("date_created", models.DateTimeField(auto_now_add=True)),
                (
                    "creator",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        related_name="result_chain_creator",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "workplan",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        related_name="result_chain_workplan",
                        to="api.workplan",
                    ),
                ),
            ],
            options={
                "db_table": "result_chain",
            },
        ),
        migrations.CreateModel(
            name="Overseer",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("name", models.CharField(max_length=500)),
                ("contact", models.CharField(max_length=500)),
                ("is_deleted", models.BooleanField(default=False)),
                ("date_created", models.DateTimeField(auto_now_add=True)),
                (
                    "title",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        related_name="overseer_title",
                        to="api.title",
                    ),
                ),
            ],
            options={
                "db_table": "overseers",
            },
        ),
        migrations.CreateModel(
            name="ObjectiveComment",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("type", models.CharField(max_length=150)),
                ("comment", models.TextField()),
                ("is_deleted", models.BooleanField(default=False)),
                ("date_created", models.DateTimeField(auto_now_add=True)),
                (
                    "goal",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        related_name="comment_goal",
                        to="api.rrigoals",
                    ),
                ),
            ],
            options={
                "db_table": "objective_comments",
            },
        ),
        migrations.CreateModel(
            name="Evaluation",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("data", models.JSONField()),
                ("is_deleted", models.BooleanField(default=False)),
                ("date_created", models.DateTimeField(auto_now_add=True)),
                (
                    "evaluator",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        related_name="evaluator",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "rri_goal",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        related_name="evaluated_rri_goal",
                        to="api.rrigoals",
                    ),
                ),
            ],
            options={
                "db_table": "evaluation",
            },
        ),
        migrations.CreateModel(
            name="Estate",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("name", models.CharField(max_length=255)),
                (
                    "ward",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        related_name="estates",
                        to="api.ward",
                    ),
                ),
            ],
            options={
                "db_table": "estates",
            },
        ),
        migrations.AddField(
            model_name="directorate",
            name="sub_sector",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.DO_NOTHING,
                related_name="sub_sector",
                to="api.subsector",
            ),
        ),
        migrations.CreateModel(
            name="CabinetMemoApprovalStatus",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("isApproved", models.BooleanField(default=False)),
                ("isDeferred", models.BooleanField(default=False)),
                ("comments", models.TextField()),
                ("is_deleted", models.BooleanField(default=False)),
                (
                    "memo",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        related_name="approval_status",
                        to="api.cabinetmemo",
                    ),
                ),
            ],
            options={
                "db_table": "cabinet_memo_approval",
            },
        ),
        migrations.CreateModel(
            name="AssignedEvaluations",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("is_evaluated", models.BooleanField(default=False)),
                ("date_created", models.DateTimeField(auto_now_add=True)),
                (
                    "evaluator",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        related_name="assigned_evaluator",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "rri_goal",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        related_name="assigned_rri_goal",
                        to="api.rrigoals",
                    ),
                ),
            ],
            options={
                "db_table": "assigned_evaluations",
            },
        ),
        migrations.CreateModel(
            name="AchievementDocuments",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("document", models.FileField(upload_to="county47_documents")),
                ("original_file_name", models.CharField(max_length=255)),
                ("file_type", models.CharField(default="FILE", max_length=500)),
                ("is_deleted", models.BooleanField(default=False)),
                ("date_created", models.DateTimeField(auto_now_add=True)),
                (
                    "achievement",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        related_name="achievement_creator",
                        to="api.achievement",
                    ),
                ),
            ],
            options={
                "db_table": "achievement_documents",
            },
        ),
        migrations.AddField(
            model_name="achievement",
            name="thematic_area",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.DO_NOTHING,
                related_name="achievement_thematic_area",
                to="api.thematicarea",
            ),
        ),
    ]
