# Generated by Django 4.2.1 on 2025-03-27 07:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0001_initial"),
    ]

    operations = [
        migrations.RenameField(
            model_name="budgetfinancialyear",
            old_name="comments",
            new_name="comment",
        ),
    ]
