# Generated by Django 4.2.1 on 2025-03-27 07:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0002_rename_comments_budgetfinancialyear_comment"),
    ]

    operations = [
        migrations.RenameField(
            model_name="budgetfinancialyear",
            old_name="comment",
            new_name="comments",
        ),
    ]
