# Generated by Django 4.2.1 on 2025-05-19 12:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_rename_comment_budgetfinancialyear_comments'),
    ]

    operations = [
        migrations.AddField(
            model_name='wave',
            name='tender_no',
            field=models.CharField(blank=True, null=True),
        ),
    ]
