# Generated by Django 4.2.1 on 2025-05-19 12:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_wave_tender_no'),
    ]

    operations = [
        migrations.RenameField(
            model_name='wave',
            old_name='tender_no',
            new_name='tender_number',
        ),
    ]
