# Generated by Django 4.2.1 on 2025-05-20 06:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_rename_tender_no_wave_tender_number'),
    ]

    operations = [
        migrations.AddField(
            model_name='wave',
            name='project_status',
            field=models.CharField(default='Not Started', max_length=255),
        ),
    ]
