# Generated by Django 4.2.1 on 2024-08-26 07:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('acl', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='user',
            table='systemsers',
        ),
    ]
