# Generated by Django 4.2.1 on 2024-08-26 07:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('acl', '0002_alter_user_table'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='user',
            table='systemusers',
        ),
    ]
